server:
  port: 8081
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db-exercies2
    username: root
    password: 1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: update

jwt:
  token:
    secret: hello
